### ISSUE TITLE
Revision version

### ISSUE THREAD

**Issue by Vikash84** [epi2me-labs/wf-denovo-assembly#2]
### What happened?

Project `epi2me-labs/wf-denovo-assembly` is currently stickied on revision: prerelease -- you need to explicitly specify a revision with the option `-r` in order to use it

### Operating System

Windows 10

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - Execution Profile

None

### Workflow Version

Project `epi2me-labs/wf-denovo-assembly` is currently stickied on revision: prerelease -- you need to explicitly specify a revision with the option `-r` in order to use it

### Relevant log output

```shell
Project `epi2me-labs/wf-denovo-assembly` is currently stickied on revision: prerelease -- you need to explicitly specify a revision with the option `-r` in order to use it
```

**Comment by cjw85** [comment]
Hi @Vikash84,

The above message is Nextflow codewords to say that you've previously selected that a particular version of the workflow be used, and that now the EPI2ME application is not specifying a version ("revision"). Why this is happening in the context of the application I do not know; but I believe you should be able to resolve it my deleting the workflow from the interface an reinstalling.

![image](https://github.com/epi2me-labs/wf-denovo-assembly/assets/3592009/66c7af43-9c58-4552-9c65-0a71e11107b4)
